### PR TITLE
Zh cn wonderflow

### PR DESCRIPTION
**Pull request by wonderflow**
commit from ZheJiang University. Work with @resouer.
translate application folder and some details in api and user.

### CODE REVIEW

**Comment by wayneeseguin** [comment]
Looks like I have a merge conflict, will have to see what's going on.

**Comment by wayneeseguin** [comment]
This is turning to be challenging, might be easier for you to rebase than for me to try to, would you be willing to do so? Thank you :smile:

**Comment by resouer** [comment]
@wayneeseguin OK, I'll have a loot at it.

**Comment by wonderflow** [comment]
I merged the conflicts. @wayneeseguin @resouer  
Some more people have translate the same area with me.

**Comment by wayneeseguin** [comment]
Thanks! I'll try to merge now.

**Pull request merged**
